-- +goose Up
-- +goose StatementBegin
CREATE TABLE USERS(
    Id SERIAL PRIMARY KEY,
    Username VARCHAR(20) NOT NULL UNIQUE,
    Email VARCHAR(30) NOT NULL UNIQUE,
    Phone VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE COMMUNICATION_TYPE(
    Id SERIAL PRIMARY KEY,
    Type VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE COMMUNICATIONS(
    Id SERIAL PRIMARY KEY,
    CommunicationTypeId INTEGER DEFAULT 0,
    UserId INTEGER,
    FOREIGN KEY (CommunicationTypeId) REFERENCES COMMUNICATION_TYPE (Id) ON DELETE SET DEFAULT,
    FOREIGN KEY (UserId) REFERENCES USERS (Id) ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE COMMUNICATIONS;

DROP TABLE COMMUNICATION_TYPE;

DROP TABLE USERS;
-- +goose StatementEnd
