-- +goose Up
-- +goose StatementBegin
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

CREATE SCHEMA MONITORING AUTHORIZATION COMMUNICATION;
CREATE SCHEMA COMM AUTHORIZATION COMMUNICATION;

CREATE TABLE MONITORING.COMMUNICATION_HISTORY(
    Id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    Communication_Type VARCHAR(10) NOT NULL,
    Delayed BOOLEAN NOT NULL,
    Phone_Number VARCHAR(15),
    Email VARCHAR(40),
    Body  TEXT,
    Completed_At TIMESTAMP NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

DROP TABLE MONITORING.COMMUNICATION_HISTORY;

DROP SCHEMA MONITORING;

DROP SCHEMA COMM;
-- +goose StatementEnd
