version: "3.7"

services:
  communication:
    image: communication-image
    volumes:
      - .:/communication:cached
    ports:
      - 4000:4000
    depends_on:
      - db
#
#  docsgenerator:
#    image: docsgenerator-image
#    volumes:
#      - .:/docsgenerator:cached
#    ports:
#      - 4001:4001
#    depends_on:
#      - db

  db:
    restart: always
    container_name: communication-db
    image: postgres:10-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5436:5432