db:
  postgres:
    host: "communication-db"
    port: "5432"
    password: "12345678"
    database: "communication"
    user: "communication"
    sslmode: "disable"

# TODO: выставить правильные параметры
mq:
  kafka:
    url: "localhost:9092"
    topic: "Docs"
    group_id: "1"

communication-service:
  queue-limit: "5"
