db:
  postgres:
    host: "communication-db"
    port: "5432"
    password: "12345678"
    database: "communication"
    user: "communication"
    sslmode: "disable"

mq:
  kafka:
    url: "kafka:9093"
    topic: "docs_topic"
    group_id: "docsgen"

communication-service:
  kafka:
    broker: "kafka:9093"
    sms-topic: "sms"
    email-topic: "email"
  message-bird:
    access-key: "OnxQzf9lwc5W9lfXFLurKx3jU"
    params: "MyReference"
    originator: "vaccine.ru"
  smtp-config:
    host: "smtp.yandex.ru"
    port: 25
    username: "noreply@shirnis-koronoy.ga"
    password: "korona12345"

