name: CI/CD Jobs

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16.3'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test -v ./...

  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16.3'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install linter framework
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
          sh -s -- -b $(go env GOPATH)/bin v1.41.1

      - name: Run linters
        run: |
          golangci-lint run

