name: Integration testing

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Go version
        with:
          stable: 'false'
          go-version: '1.16.3'
      - name: Test
        run: |
          go mod init
          go mod tidy
          go test -v ./...

